spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/lottery
     username: root
     password: 123456
     hikari:
       maxLifetime: 1765000
       maximumPoolSize: 15
       connectionTestQuery: SELECT 1
       poolName: springHikariCP
       cachePrepStmts: true
       prepStmtCacheSize: 250
       prepStmtCacheSqlLimit: 2048
       useServerPrepStmts: true

  redis:
    host: localhost
    port: 6379
    password:
    maxIdle: 300
    maxActive: 600
    maxWait: 5000
    testOnBorrow: true
    database: 1





